<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<!-- Project Settings -->
		<TargetFrameworks>
			net9.0-windows
		</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>Journey</RootNamespace>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DebugType>embedded</DebugType>
		<UseWPF>true</UseWPF>

		<!-- Build Settings -->
		<OutputPath>$(BaseOutputPath)</OutputPath>
		<AssemblyName>Journey</AssemblyName>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<!-- Metadata -->
		<Version>0.0.1</Version>
		<Description>A UI/UX experiment in visual, branching browser history.</Description>
		<Author>Simon Peckmore</Author>
		<Copyright>Copyright © Simon Peckmore 2025</Copyright>

		<!-- Package Settings -->
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

		<!-- Repository -->
		<RepositoryUrl>https://github.com/Peckmore/Journey</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>

		<!-- Analyzers -->
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

	</PropertyGroup>

	<ItemGroup>
		<None Remove="Fonts\**\*" />
		<None Remove="Images\**\*" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Fonts\**\*">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Images\**\*">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3240.44" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>