<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RootNamespace>JourneyBrowser</RootNamespace>
		<AssemblyName>JourneyBrowser</AssemblyName>
		<AssemblyTitle>Journey Browser</AssemblyTitle>
		<StartupObject>JourneyBrowser.App</StartupObject>
		<ApplicationIcon>Resources\Icons\journey.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\**\*" />
	</ItemGroup>

	<!-- Animations -->
	<ItemGroup>
		<Resource Include="Resources\Animations\**\*">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<!-- Fonts -->
	<ItemGroup>
		<Resource Include="Resources\Fonts\**\*">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<!-- Icons -->
	<ItemGroup>
		<Content Include="Resources\Icons\journey.ico" />
	</ItemGroup>

	<!-- Images -->
	<ItemGroup>
		<Resource Include="Resources\Images\**\*">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<!-- Strings -->
	<ItemGroup>
		<Compile Update="Resources\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Resources\Strings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<!-- Projects -->
	<ItemGroup>
		<ProjectReference Include="..\Journey\Journey.csproj" />
	</ItemGroup>

	<!-- Packages -->
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Dragablz" Version="0.0.3.234" />
		<PackageReference Include="LottieSharp" Version="2.4.3" />
	</ItemGroup>

</Project>